[project]
name = "bitget-telegram-bot"
version = "1.0.0"
description = "Bot de Telegram que avisa sobre criptos destacadas en Bitget."
authors = ["Mimoun.B"]
requires-python = ">=3.11"
dependencies = [
    "python-telegram-bot==13.15",
    "requests"
]
